WorkSharp/ViewModels/User/Multiply/TeamTaskBoardViewModel.cs
using System;

namespace WorkSharp.ViewModels.User.Multiply
{
    public class TeamTaskBoardViewModel
    {
        public TeamViewModel TeamViewModel { get; set; }
        public TaskBoardViewModel TaskBoardViewModel { get; set; }
        public Guid NewAdminId { get; set; }
        public Guid RemoveAdminId { get; set; }
    }
}

WorkSharp/ViewModels/User/SolutionViewModel.cs
using System;

namespace WorkSharp.ViewModels.User
{
    public class SolutionViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
    }
}

WorkSharp/Controllers/User/ProfileController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;
using WorkSharp.DAL.DbModels;
using WorkSharp.DAL.EFCoreRepository.IEntityRepositories;
using WorkSharp.ViewModels.User;

namespace WorkSharp.Controllers.User
{
    public class ProfileController : Controller
    {
        private readonly IMapper _mapper;
        private readonly UserManager<DbUser> _userManager;
        private readonly IUserRepository _userRepository;

        public ProfileController(IMapper mapper, UserManager<DbUser> userManager, IUserRepository userRepository)
        {
            _mapper = mapper;
            _userManager = userManager;
            _userRepository = userRepository;
        }

        public async Task<IActionResult> Profile()
        {
            if (TempData["ErrorMessage"] != null)
            {
                ViewBag.ErrorMessage = TempData["ErrorMessage"].ToString();
            }
            var userId = GetUserId();
            var dbUser = _userRepository.GetById(userId);
            var userViewModel = _mapper.Map<UserViewModel>(dbUser);
            ViewData["Profile"] = userViewModel;
            return View("~/Views/User/Profile/Profile.cshtml");
        }

        public async Task<IActionResult> GetProfile(Guid userId)
        {
            var dbUser = _userRepository.GetById(userId);
            var userViewModel = _mapper.Map<UserViewModel>(dbUser);
            ViewData["Profile"] = userViewModel;
            return View("~/Views/User/Profile/Profile.cshtml");
        }

        public async Task<IActionResult> EditProfile(UserViewModel userViewModel)
        {
            var userId = GetUserId();
            if (userId.Equals(userViewModel.Id))
            {
                //var dbUser = _mapper.Map<DbUser>(userViewModel);
                var dbUser = await _userManager.FindByIdAsync(userId.ToString());
                dbUser.Age = userViewModel.Age;
                dbUser.Email = userViewModel.Email;
                dbUser.Name = userViewModel.Name;
                dbUser.Surname = userViewModel.Surname;
                dbUser.Skills = userViewModel.Skills;
                dbUser.UserName = userViewModel.UserName;
                var result = await _userManager.UpdateAsync(dbUser);
                if (!result.Succeeded)
                {
                    TempData["ErrorMessage"] = result.Errors.Select(e => e.Description).Aggregate((a, b) => a + ", " + b);
                    return RedirectToAction("Profile");
                }
            }
            return RedirectToAction("Profile");
        }

        private Guid GetUserId()
        {
            return Guid.Parse((ReadOnlySpan<char>)HttpContext.User.Claims.SingleOrDefault(c => c.Type.Equals("Id"))?.Value);
        }
    }
}

WorkSharp/Controllers/User/ProjectsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WorkSharp.DAL.DbModels;
using WorkSharp.DAL.EFCoreRepository.IEntityRepositories;
using WorkSharp.ViewModels.User;
using WorkSharp.ViewModels.User.Multiply;

namespace WorkSharp.Controllers.User
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private readonly IProjectRepository _projectRepository;
        private readonly IMapper _mapper;
        private readonly UserManager<DbUser> _userManager;

        public ProjectsController(IProjectRepository projectRepository, IMapper mapper, UserManager<DbUser> userManager)
        {
            _projectRepository = projectRepository;
            _mapper = mapper;
            _userManager = userManager;
        }

        public IActionResult Projects()
        {
            var userId = GetUserId();
            var dbProjects = _projectRepository.GetUserProjects(userId);
            var projectViewModels = _mapper.Map<IEnumerable<ProjectViewModel>>(dbProjects);
            ViewData["Projects"] = projectViewModels;
            return View("~/Views/User/Projects/Projects.cshtml");
        }

        public IActionResult CreateProject(ProjectViewModel projectViewModel)
        {
            var dbProject = _mapper.Map<DbProject>(projectViewModel);
            _projectRepository.Create(dbProject, GetUserId());
            _projectRepository.Save();
            return RedirectToAction("Projects");
        }

        public IActionResult RemoveProject(Guid projectId)
        {
            var userId = GetUserId();
            var result = _projectRepository.DeleteSecure(projectId, userId);
            if (result)
            {
                _projectRepository.Save();
                return RedirectToAction("Projects");
            }
            else
            {
                return View("~/Views/AccessDenied.cshtml");
            }
        }

        public IActionResult Project(Guid projectId)
        {
            if (TempData["ErrorMessage"] != null)
            {
                ViewBag.ErrorMessage = TempData["ErrorMessage"].ToString();
            }

            ViewBag.AdminAreas = _projectRepository.IsAdmin(projectId, GetUserId());
            ViewBag.CreatorAreas = _projectRepository.IsCreator(projectId, GetUserId());
            var userId = GetUserId();
            var dbProject = _projectRepository.GetByIdSecure(projectId, userId);
            if (dbProject != null)
            {
                var projectViewModel = _mapper.Map<ProjectViewModel>(dbProject);
                ViewData["Project"] = projectViewModel;
                ViewData["Members"] = new SelectList(projectViewModel.Members, "Id", "UserName");
                ViewData["Teams"] = new SelectList(projectViewModel.TeamViewModels, "Id", "Name");
                ViewData["Admins"] = new SelectList(projectViewModel.Admins, "Id", "UserName");
                return View("~/Views/User/Projects/Project.cshtml");
            }
            else
            {
                return View("~/Views/AccessDenied.cshtml");
            }
        }

        public IActionResult GetEditProject(Guid projectId)
        {
            var userId = GetUserId();
            var dbProject = _projectRepository.GetByIdSecure(projectId, userId);
            if (dbProject != null)
            {
                var projectViewModel = _mapper.Map<ProjectViewModel>(dbProject);
                return View("~/Views/User/Projects/EditProject.cshtml", projectViewModel);
            }
            else
            {
                return View("~/Views/AccessDenied.cshtml");
            }
        }

        public IActionResult EditProject(ProjectViewModel model)
        {
            var userId = GetUserId();
            var dbProject = _mapper.Map<DbProject>(model);
            var result = _projectRepository.UpdateSecure(dbProject, userId);
            if (result)
            {
                _projectRepository.Save();
                return RedirectToAction("Project", new { projectId = model.Id });
            }
            else
            {
                return View("~/Views/AccessDenied.cshtml");
            }
        }

        public async Task<IActionResult> AddAdmin(TeamTaskBoardViewModel teamTaskBoardViewModel, Guid projectId)
        {
            var userId = teamTaskBoardViewModel.NewAdminId;
            if (_projectRepository.AddAdmin(projectId, userId))
            {
                _projectRepository.Save();
                return RedirectToAction("Project", "Projects", new { projectId });
            }

            TempData["ErrorMessage"] = "Admin Exist";
            return RedirectToAction("Project", "Projects", new { projectId });
        }

        public async Task<IActionResult> RemoveAdmin(TeamTaskBoardViewModel teamTaskBoardViewModel, Guid projectId)
        {
            if (_projectRepository.GetByIdSecure(projectId, GetUserId()).CreatorId
                .Equals(teamTaskBoardViewModel.RemoveAdminId))
            {
                TempData["ErrorMessage"] = "You are Creator :)";
                return RedirectToAction("Project", "Projects", new { projectId });
            }
            var userId = teamTaskBoardViewModel.RemoveAdminId;
            if (_projectRepository.RemoveAdmin(projectId, userId))
            {
                _projectRepository.Save();
                return RedirectToAction("Project", "Projects", new { projectId });
            }

            TempData["ErrorMessage"] = "Admin NOT Exist";
            return RedirectToAction("Project", "Projects", new { projectId });
        }

        private Guid GetUserId()
        {
            return Guid.Parse((ReadOnlySpan<char>)HttpContext.User.Claims.SingleOrDefault(c => c.Type.Equals("Id"))?.Value);
        }
    }
}

WorkSharp/Controllers/User/TaskBoardsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using WorkSharp.DAL.DbModels;
using WorkSharp.DAL.EFCoreRepository.IEntityRepositories;
using WorkSharp.ViewModels.User;
using WorkSharp.ViewModels.User.Multiply;

namespace WorkSharp.Controllers.User
{
    public class TaskBoardsController : Controller
    {
        private readonly ITaskBoardRepository _repository;
        private readonly IProjectRepository _projectRepository;
        private readonly IMapper _mapper;
        private readonly UserManager<DbUser> _userManager;

        public TaskBoardsController(ITaskBoardRepository repository, IMapper mapper, UserManager<DbUser> userManager, IProjectRepository projectRepository)
        {
            _repository = repository;
            _mapper = mapper;
            _userManager = userManager;
            _projectRepository = projectRepository;
        }

        public IActionResult TaskBoard(Guid taskBoardId)
        {
            if (TempData["ErrorMessage"] != null)
            {
                ViewBag.ErrorMessage = TempData["ErrorMessage"].ToString();
            }
            var userId = GetUserId();
            var dbTaskBoard = _repository.GetByIdSecure(taskBoardId, userId);
            var taskBoardViewModel = _mapper.Map<TaskBoardViewModel>(dbTaskBoard);
            ViewBag.AdminAreas = _projectRepository.IsAdmin(taskBoardViewModel.ProjectId, GetUserId());
            ViewData["TaskBoard"] = taskBoardViewModel;
            return View("~/Views/User/TaskBoards/TaskBoard.cshtml");
        }

        public IActionResult RemoveTaskBoard(Guid taskBoardId, string page)
        {
            if (page == "project")
            {
                var userId = GetUserId();
                var taskBoardProjectId = _repository.GetByIdSecure(taskBoardId, userId).ProjectId;
                _repository.DeleteSecure(taskBoardId, userId);
                _repository.Save();
                return RedirectToAction("Project", "Projects", new { projectId = taskBoardProjectId });
            }
            else
            {
                var userId = GetUserId();
                var taskBoard = _repository.GetByIdSecure(taskBoardId, userId);
                _repository.DeleteSecure(taskBoardId, userId);
                _repository.Save();
                return RedirectToAction("Team", "Teams", new { taskBoard.TeamId, projId = taskBoard.ProjectId });
            }
        }

        public IActionResult CreateTaskBoard(TeamTaskBoardViewModel teamTaskBoardViewModel, string page)
        {
            if (page == "project")
            {
                var taskBoardViewModel = teamTaskBoardViewModel.TaskBoardViewModel;
                var dbTaskBoard = _mapper.Map<DbTaskBoard>(taskBoardViewModel);
                _repository.Create(dbTaskBoard);
                _repository.Save();
                return RedirectToAction("Project", "Projects", new { projectId = taskBoardViewModel.ProjectId });
            }
            else
            {
                var taskBoardViewModel = teamTaskBoardViewModel.TaskBoardViewModel;
                var dbTaskBoard = _mapper.Map<DbTaskBoard>(taskBoardViewModel);
                _repository.Create(dbTaskBoard);
                _repository.Save();
                return RedirectToAction("Team", "Teams", new { taskBoardViewModel.TeamId, projId = taskBoardViewModel.ProjectId });
            }
        }

        //public IActionResult CreateTaskBoard(TaskBoardViewModel taskBoardViewModel)
        //{
        //    var dbTaskBoard = _mapper.Map<DbTaskBoard>(taskBoardViewModel);
        //    _repository.Create(dbTaskBoard);
        //    _repository.Save();
        //    return RedirectToAction("Team", "Teams", new{taskBoardViewModel.TeamId, taskBoardViewModel.ProjectId});
        //}
        private Guid GetUserId()
        {
            return _userManager.GetUserAsync(HttpContext.User).Result.Id;
        }
    }
}

WorkSharp/Controllers/User/TasksController.cs
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using WorkSharp.DAL.DbModels;
using WorkSharp.DAL.EFCoreRepository.IEntityRepositories;
using WorkSharp.ViewModels.User;

namespace WorkSharp.Controllers.User
{
    public class TasksController : Controller
    {
        private readonly ITaskRepository _repository;
        private readonly ITaskBoardRepository _taskBoardRepository;
        private readonly IProjectRepository _projectRepository;
        private readonly IMapper _mapper;
        private readonly UserManager<DbUser> _userManager;
        private readonly IWebHostEnvironment _appEnvironment;
        private readonly ISolutionRepository _solutionRepository;

        public TasksController(ISolutionRepository solutionRepository, ITaskRepository repository, IMapper mapper, UserManager<DbUser> userManager, IProjectRepository projectRepository, ITaskBoardRepository taskBoardRepository, IWebHostEnvironment appEnvironment)
        {
            _taskBoardRepository = taskBoardRepository;
            _repository = repository;
            _mapper = mapper;
            _userManager = userManager;
            _projectRepository = projectRepository;
            _appEnvironment = appEnvironment;
            _solutionRepository = solutionRepository;
        }

        public IActionResult CreateTask(TaskViewModel taskViewModel, Guid projectId)
        {
            if (_projectRepository.IsAdmin(projectId, GetUserId()))
            {
                var dbTask = _mapper.Map<DbTask>(taskViewModel);
                _repository.CreateTask(dbTask);
            }
            return RedirectToAction("TaskBoard", "TaskBoards", new { taskViewModel.TaskBoardId });
        }

        public IActionResult RemoveTask(Guid taskId, Guid projectId, Guid taskBoardId)
        {
            if (_projectRepository.IsAdmin(projectId, GetUserId()))
            {
                _repository.DeleteTask(taskId);
            }
            return RedirectToAction("TaskBoard", "TaskBoards", new { taskBoardId });
        }

        public IActionResult AddExecutor(Guid taskId, Guid taskBoardId)
        {
            var taskBoard = _taskBoardRepository.GetByIdSecure(taskBoardId, GetUserId());
            var ids = taskBoard.Team.Members.Select(m => m.Id).ToList();
            var userId = GetUserId();
            if (ids.Contains(userId))
            {
                _repository.AddExecutor(taskId, GetUserId());
            }
            else
            {
                TempData["ErrorMessage"] = "You are not member of a team :(";
            }
            return RedirectToAction("TaskBoard", "TaskBoards", new { taskBoardId });
        }

        public async Task<IActionResult> AddSolution(IFormFile solutionFile, Guid taskId, Guid taskBoardId)
        {
            var path = "/solutions/" + solutionFile.FileName;
            await using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
            {
                await solutionFile.CopyToAsync(fileStream);
            }
            var solution = new DbSolution() { Name = solutionFile.FileName, Path = path };
            _repository.AddSolution(solution, taskId);
            return RedirectToAction("TaskBoard", "TaskBoards", new { taskBoardId });
        }

        public HttpResponseMessage DownloadSolution(Guid solutionId)
        {
            var solution = _solutionRepository.GetSolution(solutionId);
            var result = new HttpResponseMessage(HttpStatusCode.OK);
            var filePath = _appEnvironment.WebRootPath + solution.Path;
            var bytes = System.IO.File.ReadAllBytes(filePath);

            result.Content = new ByteArrayContent(bytes);

            var mediaType = "application/octet-stream";
            result.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue(mediaType);
            return result;
        }

        private Guid GetUserId()
        {
            return Guid.Parse((ReadOnlySpan<char>)HttpContext.User.Claims.SingleOrDefault(c => c.Type.Equals("Id"))?.Value);
        }
    }
}

WorkSharp/Views/User/TaskBoards/TaskBoard.cshtml
@using Microsoft.AspNetCore.Components.Web
@model WorkSharp.ViewModels.User.TaskViewModel
@{
    var i = 1;
    var taskBoard = ViewData["TaskBoard"] as TaskBoardViewModel;
    var adminAreas = ViewBag.AdminAreas;
    var taskId = Guid.Empty;
}
@{
    void UpdateHeading(Guid currentTaskId)
    {
        taskId = currentTaskId;
    }
}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="~/css/projects/project.css" />
<div class="m-5 d-flex flex-column justify-content-center project-info">
    <div class="d-flex justify-content-center"> <h2>TASK BOARD</h2> </div>
    <div class="d-flex flex-column container">
        <div class="card card-body">
            <div class="d-flex justify-content-center align-items-center">
                <div>
                    <h3>Name: @taskBoard.Name</h3><br />
                    <h4>Info: @taskBoard.Type</h4>
                </div>
            </div>
        </div>
    </div>
    <div class="d-flex mt-5 justify-content-center">
        <div class="d-flex flex-column align-items-center w-75">
            <div class="card align-items-center w-75">
                <div class="d-flex align-items-center">
                    @if (adminAreas)
                    {
                        <div class="wrap">
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-task-modal-new">
                                Add Task
                            </button>
                        </div>
                    }
                </div>
                @if (taskBoard.TaskViewModels.Any())
                {
                    <table class="table project-table">
                        <thead>
                            <tr>
                                <th scope="col" class="number">#</th>
                                <th scope="col" class="name">Name</th>
                                <th scope="col" class="name">Info</th>
                                <th scope="col" class="name">Deadline</th>
                                <th scope="col" class="info">Executor</th>
                                <th scope="col" class="info">Solution</th>
                                @if (adminAreas)
                                {
                                    <th scope="col" class="remove">Remove</th>
                                }
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var task in taskBoard.TaskViewModels)
                            {
                                <tr>
                                    <th scope="row">@i</th>
                                    <td><span>@task.Name</span></td>
                                    <td><span>@task.Info</span></td>
                                    <td><span>@task.Deadline.ToString("dd/MM/yyyy")</span></td>
                                    <td>
                                        @if (task.Executor != null)
                                        {
                                            <a asp-controller="Profile" asp-action="Profile" asp-route-projectId="@task.ExecutorId">@task.Executor.UserName</a>
                                        }
                                        else
                                        {
                                            <a asp-controller="Tasks" asp-action="AddExecutor" asp-route-taskBoardId="@taskBoard.Id" asp-route-taskId="@task.Id" class="btn btn-success btn-sm">
                                                <span class="glyphicon glyphicon-remove"></span> Take task
                                            </a>
                                        }
                                    </td>
                                    <td>
                                        @if (task.ExecutorId.Equals(Guid.Parse(User.Claims.SingleOrDefault(c => c.Type.Equals("Id"))?.Value)) && task.Solution == null)
                                        {
                                            <button id="addSolution" taskId="@task.Id.ToString()" type="button" class="btn btn-success btn-sm addSolution" data-toggle="modal" data-target=".bs-solution-modal-new">
                                                Add Solution
                                            </button>

                                        }
                                        else if (task.Solution != null)
                                        {
                                            <a href="@Url.Content(task.Solution.Path)">Download @task.Solution.Name</a>
                                        }
                                        else
                                        {
                                            <span class="btn btn-secondary disabled btn-sm">
                                                <span class="glyphicon glyphicon-remove"></span> Waiting for solution
                                            </span>
                                        }
                                    </td>
                                    @if (adminAreas)
                                    {
                                        <td>
                                            <a asp-controller="Tasks" asp-action="RemoveTask" asp-route-taskId="@task.Id" asp-route-taskBoardId="@task.TaskBoardId" asp-route-projectId="@taskBoard.ProjectId" class="btn btn-danger btn-sm">
                                                <span class="glyphicon glyphicon-remove"></span> Remove
                                            </a>
                                        </td>
                                    }
                                </tr>
                                i++;

                            }
                        </tbody>
                    </table>
                }
            </div>
        </div>
    </div>
</div>
<div class="modal fade bs-task-modal-new" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">

    <div class="modal-dialog">

        <!-- Modal Content: begins -->
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>

            <!-- Modal Body -->
            <form asp-controller="Tasks" asp-action="CreateTask" asp-route-projectId="@taskBoard.ProjectId">
                <div class="modal-body">
                    <div class="body-message">
                        <h4>Any Heading</h4>
                        <input class="form-control" type="text" asp-for="TaskBoardId" style="display: none" value="@taskBoard.Id" /><br />
                        <label>Task  name:</label>
                        <input class="form-control" type="text" asp-for="Name" /><br />
                        <label>Task info:</label>
                        <input class="form-control" type="text" asp-for="Info" /><br />
                        <label>Task deadline:</label>
                        <input class="form-control" type="date" asp-for="Deadline" /><br />
                    </div>
                </div>

                <!-- Modal Footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
        <!-- Modal Content: ends -->
    </div>
</div>
<div class="modal fade bs-solution-modal-new" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">

    <div class="modal-dialog">

        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>

            <form id="solution" asp-controller="Tasks" asp-action="AddSolution" asp-route-taskBoardId="@taskBoard.Id" enctype="multipart/form-data">
                <div class="modal-body">
                    <div class="body-message">
                        <h4>Any Heading</h4>
                        <input type="file" id="inputGroupFile02" name="solutionFile"><br />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="error-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-modal="true" style="display: none;">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header d-flex justify-content-center">
                <h4 class="modal-title text-center" id="myModalLabel">Error</h4>
            </div>
            <div class="modal-body d-flex justify-content-center">
                <h3>@ViewBag.ErrorMessage</h3>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function (e) {
    $('.addSolution').click(function (event) {
        let id = event.target.getAttribute('taskId');
        console.log(id);
        let action = $('#solution').attr('action');
        action += "&taskId=" + id;
        $('#solution').attr('action', action);
    })
        });
</script>
@if (ViewBag.ErrorMessage != null)
{
    <script>
    $('#error-modal').modal('show');
    </script>
}