WorkSharp/Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WorkSharp.DAL.DbModels;
using WorkSharp.DAL.EFCoreRepository;
using WorkSharp.ViewModels.Authentication;

namespace WorkSharp.Controllers
{
    public class AuthenticationController : Controller
    {
        private IMapper _mapper;
        private UserManager<DbUser> _userManager;
        private SignInManager<DbUser> _signInManager;

        public AuthenticationController(IMapper mapper, UserManager<DbUser> userManager, SignInManager<DbUser> signInManager)
        {
            _mapper = mapper;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (!ModelState.IsValid) return View("Register", model);
            DbUser user = _mapper.Map<DbUser>(model);
            var claims = new List<Claim>
            {
                new Claim("Name", model.UserName),
                new Claim("Email", model.Email)
            };
            await _userManager.CreateAsync(user, model.Password);
            await _userManager.AddClaimsAsync(user, claims);

            return RedirectToAction("Login");
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (!ModelState.IsValid) return View("Login", model);
            var result = await _signInManager.PasswordSignInAsync(model.Login, model.Password, false, false);
            if (result.Succeeded)
            {
                return RedirectToAction("Index", "Main");
            }
            else
            {
                ModelState.AddModelError("", "Неправильный логин и (или) пароль");
            }
            return View("Login", model);
        }
        [Authorize]
        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Main");
        }
    }
}

WorkSharp/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;

namespace WorkSharp.Controllers
{
    public class MainController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WorkSharp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>WorkSharp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/bootstrap.css" />
    <link rel="stylesheet" href="~/css/main.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <a class="navbar-brand" href="#">WorkSharp</a>
            <div class="collapse navbar-collapse" id="navbarsExample04">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Main" asp-action="Index">Home</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Projects" asp-action="Projects">My Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Profile" asp-action="Profile">Profile</a>
                        </li>
                    }
                </ul>
                <form class="form-inline my-2 my-md-0">
                    <ul class="navbar-nav mr-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Authentication" asp-action="LogOut">Log Out</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Authentication" asp-action="Login">Log in</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Authentication" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </form>
            </div>
        </nav>
    </header>
    @RenderBody()
</body>
</html>